// <auto-generated />
using System;
using InventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace InventoryManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116152815_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryAllowedUsers", b =>
                {
                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("InventoryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryAllowedUsers", (string)null);
                });

            modelBuilder.Entity("InventoryManagement.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("SalesforceAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("SalesforceAccountId")
                        .HasColumnType("text");

                    b.Property<string>("SalesforceContactId")
                        .HasColumnType("text");

                    b.Property<string>("SalesforceInstanceUrl")
                        .HasColumnType("text");

                    b.Property<string>("SalesforceRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SalesforceTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(\"FirstName\", '') || ' ' || coalesce(\"LastName\", '') || ' ' || coalesce(\"Email\", ''))", true);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("SequentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SequentialId"));

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Email"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Email"), new[] { "gin_trgm_ops" });

                    b.HasIndex("FirstName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FirstName"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FirstName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("LastName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastName"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("LastName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("InventoryManagement.Models.Discussion.DiscussionPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("InventoryId", "CreatedAtUtc");

                    b.ToTable("DiscussionPosts", (string)null);
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.CustomId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CustomIds");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomId_Id")
                        .HasColumnType("integer");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint");

                    b.Property<char?>("SeparatorAfter")
                        .HasColumnType("character(1)");

                    b.Property<char?>("SeparatorBefore")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("CustomId_Id");

                    b.ToTable("AbstractElement");

                    b.HasDiscriminator<string>("ElementType").HasValue("AbstractElement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomIdId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Owner_UserId")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(\"Title\", '') || ' ' || coalesce(\"Description\", ''))", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CustomIdId");

                    b.HasIndex("Description");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Owner_UserId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("Title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("InventoryManagement.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BoolLine1")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BoolLine2")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BoolLine3")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkLine1")
                        .HasColumnType("text");

                    b.Property<string>("LinkLine2")
                        .HasColumnType("text");

                    b.Property<string>("LinkLine3")
                        .HasColumnType("text");

                    b.Property<string>("MultiLine1")
                        .HasColumnType("text");

                    b.Property<string>("MultiLine2")
                        .HasColumnType("text");

                    b.Property<string>("MultiLine3")
                        .HasColumnType("text");

                    b.Property<double?>("NumericLine1")
                        .HasColumnType("double precision");

                    b.Property<double?>("NumericLine2")
                        .HasColumnType("double precision");

                    b.Property<double?>("NumericLine3")
                        .HasColumnType("double precision");

                    b.Property<string>("Owner_UserId")
                        .HasColumnType("text");

                    b.Property<string>("SingleLine1")
                        .HasColumnType("text");

                    b.Property<string>("SingleLine2")
                        .HasColumnType("text");

                    b.Property<string>("SingleLine3")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Owner_UserId");

                    b.HasIndex("InventoryId", "CustomId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InventoryManagement.Models.ItemLike", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.HasKey("ItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ItemLikes", (string)null);
                });

            modelBuilder.Entity("InventoryTags", b =>
                {
                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("InventoryId", "TagId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("TagId");

                    b.ToTable("InventoryTags", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.Bit20Element", b =>
                {
                    b.HasBaseType("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement");

                    b.Property<char?>("PaddingChar")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("character(1)");

                    b.Property<int>("Radix")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Bit20");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.Bit32Element", b =>
                {
                    b.HasBaseType("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement");

                    b.Property<char?>("PaddingChar")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("character(1)");

                    b.Property<int>("Radix")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Bit32");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.DateTimeElement", b =>
                {
                    b.HasBaseType("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement");

                    b.Property<string>("DateTimeFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("DateTime");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.Digit6Element", b =>
                {
                    b.HasBaseType("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement");

                    b.Property<char?>("PaddingChar")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("character(1)");

                    b.Property<int>("Radix")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Digit6");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.Digit9Element", b =>
                {
                    b.HasBaseType("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement");

                    b.Property<char?>("PaddingChar")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("character(1)");

                    b.Property<int>("Radix")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Digit9");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.FixedTextElement", b =>
                {
                    b.HasBaseType("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement");

                    b.Property<string>("FixedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("FixedText");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.GuidElement", b =>
                {
                    b.HasBaseType("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement");

                    b.HasDiscriminator().HasValue("Guid");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.SequentialElement", b =>
                {
                    b.HasBaseType("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement");

                    b.Property<char?>("PaddingChar")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("character(1)");

                    b.Property<int>("Radix")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Sequential");
                });

            modelBuilder.Entity("InventoryAllowedUsers", b =>
                {
                    b.HasOne("InventoryManagement.Models.Inventory.Inventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryAllowedUsers_InventoryId");

                    b.HasOne("InventoryManagement.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryAllowedUsers_UserId");
                });

            modelBuilder.Entity("InventoryManagement.Models.Discussion.DiscussionPost", b =>
                {
                    b.HasOne("InventoryManagement.Models.Inventory.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DiscussionPost_Inventory");

                    b.HasOne("InventoryManagement.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DiscussionPost_User");

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.Element.AbstractElement", b =>
                {
                    b.HasOne("InventoryManagement.Models.Inventory.CustomId.CustomId", "CustomId")
                        .WithMany("Elements")
                        .HasForeignKey("CustomId_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomId");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.Inventory", b =>
                {
                    b.HasOne("InventoryManagement.Models.Inventory.Category", "Category")
                        .WithMany("Inventories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Models.Inventory.CustomId.CustomId", "CustomId")
                        .WithMany()
                        .HasForeignKey("CustomIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Models.AppUser", "Owner")
                        .WithMany("OwnedInventories")
                        .HasForeignKey("Owner_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Inventory_Owner");

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "BoolLine1", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "BoolLine2", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "BoolLine3", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "LinkLine1", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "LinkLine2", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "LinkLine3", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "MultiLine1", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "MultiLine2", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "MultiLine3", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "NumericLine1", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "NumericLine2", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "NumericLine3", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "SingleLine1", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "SingleLine2", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("InventoryManagement.Models.Inventory.CustomField", "SingleLine3", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("boolean");

                            b1.Property<short?>("Position")
                                .HasColumnType("smallint");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.Navigation("BoolLine1");

                    b.Navigation("BoolLine2");

                    b.Navigation("BoolLine3");

                    b.Navigation("Category");

                    b.Navigation("CustomId");

                    b.Navigation("LinkLine1");

                    b.Navigation("LinkLine2");

                    b.Navigation("LinkLine3");

                    b.Navigation("MultiLine1");

                    b.Navigation("MultiLine2");

                    b.Navigation("MultiLine3");

                    b.Navigation("NumericLine1");

                    b.Navigation("NumericLine2");

                    b.Navigation("NumericLine3");

                    b.Navigation("Owner");

                    b.Navigation("SingleLine1");

                    b.Navigation("SingleLine2");

                    b.Navigation("SingleLine3");
                });

            modelBuilder.Entity("InventoryManagement.Models.Item", b =>
                {
                    b.HasOne("InventoryManagement.Models.Inventory.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Item_Inventory");

                    b.HasOne("InventoryManagement.Models.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("Owner_UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Item_Owner");

                    b.Navigation("Inventory");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InventoryManagement.Models.ItemLike", b =>
                {
                    b.HasOne("InventoryManagement.Models.Item", "Item")
                        .WithMany("Likes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemLike_Item");

                    b.HasOne("InventoryManagement.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemLike_User");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryTags", b =>
                {
                    b.HasOne("InventoryManagement.Models.Inventory.Inventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTags_InventoryId");

                    b.HasOne("InventoryManagement.Models.Inventory.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTags_TagId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InventoryManagement.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InventoryManagement.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InventoryManagement.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagement.Models.AppUser", b =>
                {
                    b.Navigation("OwnedInventories");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.Category", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.CustomId.CustomId", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("InventoryManagement.Models.Inventory.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryManagement.Models.Item", b =>
                {
                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
